name: Build and Deploy DocFX Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Build DocFX site
      run: docfx build 

    #- name: Deploy to Azure Function App
      #uses: azure/functions-action@v1
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        #app-name: 'CustomerAdoptionGuide'
        app-name: 'CustomerAdoptionGuideWeb'
        package: './_site'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_WEB }}
        #publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
