name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate Azure DevOps NuGet feed
      uses: NuGet/setup-nuget@v1

    - name: Install docfx
      run: dotnet tool update -g docfx

    - name: Run docfx
      run: |
        docfx ./docfx.json
        if [ $? -ne 0 ]; then
          echo "docfx build failed with exit code $?."
          exit 1
        fi

    - name: Upload artifact to Azure Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch -d '$web' -s ./_site --account-name devpmssa001 --account-key ${{ secrets.AZURE_STORAGE_KEY }}
          
    - name: Azure App Service Deploy - Documentation website
      uses: azure/webapps-deploy@v2
      with:
        app-name: CAGtest
        slot-name: production
        package: ./_site
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_CAGtest }}