name: Build and Deploy

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install DocFX
        run: choco install docfx -y
        env:
          CI: true

      - name: Build documentation
        run: docfx build

      - name: Verify _site directory
        run: |
          if [ -d "_site" ]; then
            echo "_site directory exists."
          else
            echo "_site directory does not exist."
            exit 1
          fi

      - name: List contents of _site directory
        run: |
          echo "Listing contents of _site directory:"
          ls -la _site

      - name: Publish results
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: _site
          path: _site

      - name: Deploy to Azure Web App
        id: builddeploy
        uses: azure/webapps-deploy@v4
        with:
          app-name: 'CustomerAdoptionGuideWeb'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_WEB }}
          action: 'upload'
          skip_app_build: true
          app_location: '_site'