name: Build

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: choco install docfx
        run: |
          choco install docfx -y
        env:
          CI: true
      - name: build documentation
        run: |
          docfx build
      - name: Zip _site folder
        run: zip -r site.zip ./_site
      - name: publish results
        uses: actions/upload-artifact@v4
        with:
          name: site.zip
          path: ./site.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site.zip
          path: ./site.zip
      - name: Deploy
        id: builddeploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CustomerAdoptionGuideWeb'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_WEB }}
          action: "upload"
          skip_app_build: true
          app_location: "_site" 