name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Build documentation
      run: docfx build

    - name: Generate build info
      run: |
        if [ ! -d "D:\\a\\CustomerAdoptionGuide\\CustomerAdoptionGuide\\obj\\.cache\\build" ]; then
          mkdir -p D:\\a\\CustomerAdoptionGuide\\CustomerAdoptionGuide\\obj\\.cache\\build
        fi
        echo "Build information" > D:\\a\\CustomerAdoptionGuide\\CustomerAdoptionGuide\\obj\\.cache\\build\\build.info
      shell: bash

    - name: Publish results
      uses: actions/upload-artifact@v4
      with:
        name: _site
        path: _site/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: _site
          path: _site

      - name: Deploy to Azure Web App
        id: builddeploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CustomerAdoptionGuideWeb'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_WEB }}
          package: '_site'