name: Build and Deploy DocFX Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Build DocFX site
      run: docfx build 
    
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r dir.zip dir

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'CustomerAdoptionGuideWeb'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_WEB  }}
        publish_dir: CUSTOMERADOPTIONGUIDE/_site
        force_orphan: true
